tunnel: 35a2d83d-aa45-4ad0-a1ad-b0735a66fa63
credentials-file: /Users/onparmarketing/.cloudflared/35a2d83d-aa45-4ad0-a1ad-b0735a66fa63.json

ingress:
  - hostname: onparbev.com
    service: http://localhost:3000
  - hostname: www.onparbev.com
    service: http://localhost:3000
  - service: http_status:404
